services:
  db:
    image: mysql:latest
    container_name: hotelSharingDatabase
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: default
    volumes:
      - my-db:/var/ lib/mysql
    ports:
      - '2000:3306'
volumes:
    my-db:
