services:
  db:
    image: mysql:latest
    container_name: hotelSharingDatabase
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: default
    volumes:
      - my-db:/var/ lib/mysql
    ports:
      - '2000:3306'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app/frontend
    user: "1000:1000"
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "8081:8080"
    command: [ "npm", "run", "serve" ]
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
      - ./api/build/libs/api-0.0.1-SNAPSHOT.jar:/app/api/build/libs/api-0.0.1-SNAPSHOT.jar
    ports:
      - 8080:8080
      - 35729:35729
    depends_on:
      - db
    #    command: ['java', '-jar', 'build/libs/api-0.0.1-SNAPSHOT.jar']
    command: [ './gradlew', 'bootRun' ]
volumes:
    my-db:
